### ISSUE TITLE
Redshift Connector not working in Python 3.6

### ISSUE THREAD

**Issue by crayolakat** [move-coop/parsons#518]
When trying to use the Redshift connector in Python 3.6, this line:
`import parsons.databases.redshift.constants as consts`
in the `parsons/databases/redshift/re_create_table.py` file causes the following error:
`AttributeError: module 'parsons.databases' has no attribute 'redshift'` and the connector fails to work correctly.

The issue does not occur in Python 3.7 or Python 3.8.

**Comment by thebbennett** [comment]
Note to contributors: Reproduce this error

**Comment by crayolakat** [comment]
Hi, here are the reproduction steps:

1. Create a Python 3.6.11 environment. (I use `pyenv` for Python version management)
2. Create a new directory with the following files:
test.py:
```
import os
os.environ['PARSONS_SKIP_IMPORT_ALL'] = '1'
import parsons.databases.redshift.constants as consts

print('Test')

```

requirements.txt:
```
boto3==1.17.98
petl==1.6.8

```
3. cd into the directory you created and activate your Python 3.6.11 environment
4. Run the following command: `pip install --no-deps -e git+https://github.com/move-coop/parsons.git@master#egg=parsons`
5. Run the following command: `pip install -r requirements.txt`
6. Run the following command: `python test.py`. You will get the following error:
(test-ve) kathynguyen@administrators-MacBook-Pro Test % python test.py                 
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import parsons.databases.redshift.constants as consts
  File "/Users/kathynguyen/.pyenv/versions/3.6.11/envs/test-ve/src/parsons/parsons/databases/redshift/__init__.py", line 1, in <module>
    from parsons.databases.redshift.redshift import Redshift
  File "/Users/kathynguyen/.pyenv/versions/3.6.11/envs/test-ve/src/parsons/parsons/databases/redshift/redshift.py", line 3, in <module>
    from parsons.databases.redshift.rs_create_table import RedshiftCreateTable
  File "/Users/kathynguyen/.pyenv/versions/3.6.11/envs/test-ve/src/parsons/parsons/databases/redshift/rs_create_table.py", line 1, in <module>
    from parsons.databases.database.database import DatabaseCreateStatement
  File "/Users/kathynguyen/.pyenv/versions/3.6.11/envs/test-ve/src/parsons/parsons/databases/database/__init__.py", line 1, in <module>
    from parsons.databases.database.database import DatabaseCreateStatement
  File "/Users/kathynguyen/.pyenv/versions/3.6.11/envs/test-ve/src/parsons/parsons/databases/database/database.py", line 1, in <module>
    import parsons.databases.database.constants as consts
AttributeError: module 'parsons.databases' has no attribute 'database'
```

**Comment by dannyboy15** [comment]
given that support for `python3.6` was dropped in #664, should we close this?

**Comment by crayolakat** [comment]
I'm fine with closing this.
